In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/RASIL-RISAM/-covid-research-/main/all_training.csv")
df

Unnamed: 0  Sex   Age    CA     CK   CREA    ALP    GGT    GLU  \
0     A00345_2020-03-25  1.0  82.0  2.09    NaN  1.150   95.0   40.0   78.0   
1     A00791_2020-03-19  1.0  51.0  1.97  237.0  0.970   54.0   98.0   98.0   
2     A00741_2020-03-04  1.0  58.0  2.11    NaN  1.000   80.0  147.0  106.0   
3     A00605_2020-04-15  0.0  82.0  2.27  138.0  0.755  123.5  176.5  106.0   
4     A00417_2020-02-24  1.0  79.0  2.07   73.0  1.810   62.0   36.5   96.0   
...                 ...  ...   ...   ...    ...    ...    ...    ...    ...   
1731                 49  0.0   NaN  2.38   40.0  0.800   68.0    9.0  128.0   
1732                 50  0.0   NaN  2.36    NaN  0.960   79.0   35.0  107.0   
1733                 51  1.0   NaN  2.28    NaN  1.420    NaN    NaN  136.0   
1734                 52  1.0   NaN  2.40  124.0  0.950   48.0   44.0   95.0   
1735                 53  1.0   NaN  2.14    NaN  1.040    NaN    NaN  179.0   

        AST  ...    MO   EO   BA   NET   LYT  MOT  EOT  BAT  Suspect  target  
0      26.0  ...   9.5  2.9  0.5  6.40  1.20  0.8  0.3  0.0      1.0       0  
1      74.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       1  
2      41.0  ...   7.3  0.3  0.1  5.45  0.75  0.5  0.0  0.0      1.0       0  
3     114.0  ...   9.5  1.7  0.9  3.60  2.60  0.7  0.1  0.1      0.5       0  
4      28.0  ...  10.0  8.5  0.5  0.40  0.50  0.1  0.1  0.0      1.0       0  
...     ...  ...   ...  ...  ...   ...   ...  ...  ...  ...      ...     ...  
1731   13.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       0  
1732   24.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       0  
1733   53.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       0  
1734   50.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       0  
1735   28.0  ...   NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN      1.0       0  

[1736 rows x 36 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'Sex', 'Age', 'CA', 'CK', 'CREA', 'ALP', 'GGT', 'GLU',
       'AST', 'ALT', 'LDH', 'PCR', 'KAL', 'NAT', 'UREA', 'WBC', 'RBC', 'HGB',
       'HCT', 'MCV', 'MCH', 'MCHC', 'PLT1', 'NE', 'LY', 'MO', 'EO', 'BA',
       'NET', 'LYT', 'MOT', 'EOT', 'BAT', 'Suspect', 'target'],
      dtype='object')

In [4]:
df.shape

(1736, 36)

In [5]:
df = df.dropna()
df.shape

(324, 36)

In [6]:
normal_ranges = {
    'CK': (5, 25),  # Normal range for CK
    'CREA': (0.74, 1.35),  # Normal range for CREA in males
    'GGT': (7, 47),  # Normal range for GGT in males
}

In [7]:
for param, (lower, upper) in normal_ranges.items():
    df[f'{param}_Normal'] = ((df[param] >= lower) & (df[param] <= upper)).astype(int)

# Calculate ratios or differences between pairs of parameters
df['CK_CREARatio'] = df['CK'] / df['CREA']
df['CREA_GLURatio'] = df['CREA'] / df['GLU']

<ipython-input-7-918293c1303e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{param}_Normal'] = ((df[param] >= lower) & (df[param] <= upper)).astype(int)
<ipython-input-7-918293c1303e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{param}_Normal'] = ((df[param] >= lower) & (df[param] <= upper)).astype(int)
<ipython-input-7-918293c1303e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See t

In [8]:
df.head()

Unnamed: 0  Sex   Age    CA     CK      CREA    ALP    GGT  \
3   A00605_2020-04-15  0.0  82.0  2.27  138.0  0.755000  123.5  176.5   
4   A00417_2020-02-24  1.0  79.0  2.07   73.0  1.810000   62.0   36.5   
5   A01643_2020-04-01  1.0  84.0  2.06  115.0  1.283333   75.0   75.0   
12  A01477_2020-04-21  0.0  53.0  2.36   45.5  0.593333   62.0   21.5   
13  A01399_2020-03-22  0.0  76.0  2.20  349.0  2.420000  159.5  147.0   

           GLU     AST  ...   MOT   EOT  BAT  Suspect  target  CK_Normal  \
3   106.000000   114.0  ...  0.70  0.10  0.1      0.5       0          0   
4    96.000000    28.0  ...  0.10  0.10  0.0      1.0       0          0   
5    95.500000    40.5  ...  0.25  0.05  0.0      0.0       1          0   
12   91.666667    36.0  ...  0.60  0.05  0.0      1.0       0          0   
13  640.000000  1018.5  ...  1.25  0.00  0.0      0.5       1          0   

    CREA_Normal  GGT_Normal  CK_CREARatio  CREA_GLURatio  
3             1           0    182.781457       0.007123  
4             0           1     40.331492       0.018854  
5             1           0     89.610390       0.013438  
12            0           1     76.685393       0.006473  
13            0           0    144.214876       0.003781  

[5 rows x 41 columns]

In [9]:
x=df[['Age','CK_CREARatio','CREA_GLURatio','ALP','AST', 'ALT','LDH','RBC',
       'MCV','MO','BA','EOT']]
x

Age  CK_CREARatio  CREA_GLURatio    ALP     AST    ALT    LDH  \
3     82.0    182.781457       0.007123  123.5   114.0   63.0  281.0   
4     79.0     40.331492       0.018854   62.0    28.0   38.5  264.0   
5     84.0     89.610390       0.013438   75.0    40.5   27.0  364.5   
12    53.0     76.685393       0.006473   62.0    36.0   35.5  269.5   
13    76.0    144.214876       0.003781  159.5  1018.5  559.5  694.0   
...    ...           ...            ...    ...     ...    ...    ...   
1606  52.0    169.230769       0.003714   85.0    27.0   34.0  196.0   
1619  80.0     72.058824       0.006018   95.0    22.0   15.5  319.0   
1644  68.0     27.616279       0.008843   58.0    12.2   16.4  185.0   
1650  79.0     59.375682       0.005473   44.0    46.3   33.7  422.3   
1678  58.0    107.239819       0.007342   42.0    21.0   35.0  242.5   

           RBC        MCV     MO    BA    EOT  
3     5.000000  84.600000   9.50  0.90  0.100  
4     2.906667  98.433333  10.00  0.50  0.100  
5     4.373333  89.333333   6.80  0.60  0.050  
12    4.325000  87.400000  10.65  0.40  0.050  
13    4.125000  72.950000   7.25  0.05  0.000  
...        ...        ...    ...   ...    ...  
1606  4.840000  85.300000  12.40  0.70  0.300  
1619  4.130000  86.300000   3.50  0.00  0.000  
1644  3.186000  95.220000   7.44  0.38  0.072  
1650  3.279000  85.700000   4.30  0.17  0.286  
1678  4.210000  90.600000  11.80  0.10  0.050  

[324 rows x 12 columns]

In [10]:
y=df[['target']]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.20, random_state=0)

In [12]:
from sklearn.preprocessing import MinMaxScaler
st_x= MinMaxScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [13]:
x_train

array([[7.43902439e-01, 1.43696578e-02, 2.21437687e-01, ...,
        1.32867133e-01, 1.78571429e-01, 0.00000000e+00],
       [8.29268293e-01, 7.70225837e-04, 1.05998430e-01, ...,
        5.66433566e-01, 7.14285714e-02, 6.89655172e-02],
       [5.12195122e-01, 7.79238938e-03, 4.80938312e-02, ...,
        8.39160839e-02, 1.42857143e-01, 0.00000000e+00],
       ...,
       [7.56097561e-01, 3.86023305e-03, 3.32868855e-01, ...,
        5.20104895e-01, 3.21428571e-01, 1.72413793e-02],
       [5.60975610e-01, 1.14896662e-02, 5.73627976e-03, ...,
        1.85314685e-01, 1.07142857e-01, 0.00000000e+00],
       [6.95121951e-01, 4.86205890e-03, 9.30207003e-02, ...,
        1.67832168e-01, 2.14285714e-01, 0.00000000e+00]])

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [15]:
y_pred= classifier.predict(x_test)

In [16]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.62      0.78      0.69        23
           1       0.86      0.74      0.79        42

    accuracy                           0.75        65
   macro avg       0.74      0.76      0.74        65
weighted avg       0.78      0.75      0.76        65



In [17]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[18  5]
 [11 31]]


In [18]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Train the classifier
clf.fit(x_train, y_train)

# Get feature importances
feature_importances = clf.feature_importances_

# Create a DataFrame to display feature importances
feature_importance_df = pd.DataFrame({'Feature': x.columns, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Print feature importances
print(feature_importance_df)


<ipython-input-18-f4b67926a9cd>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(x_train, y_train)


          Feature  Importance
6             LDH    0.205491
4             AST    0.130930
10             BA    0.099575
5             ALT    0.092976
7             RBC    0.081070
0             Age    0.068793
11            EOT    0.068328
3             ALP    0.060797
9              MO    0.056034
1    CK_CREARatio    0.050953
8             MCV    0.044915
2   CREA_GLURatio    0.040137


In [19]:
from sklearn.model_selection import GridSearchCV

# Define a range of values for n_neighbors to be tested
param_grid = {'n_neighbors': np.arange(1, 21)}

# Initialize the KNN classifier
knn = KNeighborsClassifier()

# Perform grid search with cross-validation
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_

# Evaluate the model with the best hyperparameters on the test set
best_knn = grid_search.best_estimator_
y_pred = best_knn.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for 

In [20]:
# Print classification report and confusion matrix
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.83      0.76        23
           1       0.89      0.81      0.85        42

    accuracy                           0.82        65
   macro avg       0.80      0.82      0.81        65
weighted avg       0.83      0.82      0.82        65

Confusion Matrix:
[[19  4]
 [ 8 34]]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [22]:
from sklearn.preprocessing import MinMaxScaler
st_x= MinMaxScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [23]:
from sklearn.naive_bayes import GaussianNB
classifier2 = GaussianNB()
classifier2.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [24]:
y_pred2 = classifier2.predict(x_test)

In [25]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred2)
print(cr)

              precision    recall  f1-score   support

           0       0.69      0.74      0.71        27
           1       0.87      0.83      0.85        54

    accuracy                           0.80        81
   macro avg       0.78      0.79      0.78        81
weighted avg       0.81      0.80      0.80        81



In [26]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred2)
print(cm)

[[20  7]
 [ 9 45]]


In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB

# Initialize Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Define parameters grid (no specific parameters for GaussianNB)
param_grid = {}

# Perform grid search with cross-validation
grid_search = GridSearchCV(gnb, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Get the best estimator
best_gnb = grid_search.best_estimator_

# Print the best parameters
print("Best Parameters:", grid_search.best_params_)

# Evaluate the best model on the test set
y_pred = best_gnb.predict(x_test)

# Print classification report and confusion matrix
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Best Parameters: {}
Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.74      0.71        27
           1       0.87      0.83      0.85        54

    accuracy                           0.80        81
   macro avg       0.78      0.79      0.78        81
weighted avg       0.81      0.80      0.80        81

Confusion Matrix:
[[20  7]
 [ 9 45]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam